let shopItemsData = [
    {
      id: "klhtvpohret",
      name: "Laptop",
      price: 1200,
      desc: "lenovo laptop for full stack development.",
      img: "images/img-1.jpg",
    },
    {
      id: "fhbewhbv",
      name: "Mouse",
      price: 20,
      desc: "fastest mouse in the world and it works with Bluetooth.",
      img: "images/img-2.jpg",
    },
    {
      id: "wuefbncxbsn",
      name: "Keyboard",
      price: 50,
      desc: "just buy it and it will write itself.",
      img: "images/img-3.png",
    },
    {
      id: "thyfhcbcv",
      name: "Headphone",
      price: 80,
      desc: "just say lala and it will finish the song itself.",
      img: "images/img-4.webp",
    },
    {
      id: "thiecbawdjksadjk",
      name: "Hard Drive",
      price: 100,
      desc: "five million terabytes,17 operating system included",
      img: "images/img-5.jpeg",
    },
    {
      id: "iuertrywebncdjksadjk",
      name: "Printer",
      price: 150,
      desc: "i have this printer and i use it so good.",
      img: "images/img-6.jpg",
    },
    {
      id: "thierytbvcbvzdhadjk",
      name: "Desk chair",
      price: 120,
      desc: "There is no better chair, it makes you sleep.",
      img: "images/img-7.jpeg",
    },
    {
      id: "trfoiwfcnbcawdjksadjk",
      name: "Coffe Macker",
      price: 30,
      desc: "just look at it, the coffee machine makes coffee ",
      img: "images/img-8.webp",
    },
    {
      id: "cbvxbcvsceldk",
      name: "Blue Tooth Speaker",
      price: 60,
      desc: "not for sale, i tell you not for sale.",
      img: "images/img-9.jpeg",
    },
    {
      id: "oiopijmjkhuihb",
      name: "Desk Lamp",
      price: 25,
      desc: "buy this lamp because it is so bad.",
      img: "images/img-10.jpeg",
    },
    {
      id: "oiopijewyiohbjhib",
      name: "Flash",
      price: 0.99,
      desc: "Ruby ducky flash , just working on windows.",
      img: "images/img-11.webp",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "3lawe",
      price: 10000000,
      desc: "ba zamane awae bbe ba doctor,zor xuen sherena.",
      img: "images/img-12.jpg",
    },
  ];
  